# Site settings
title: Lorem Ipsum
email: flomertens@gmail.com
description: "Work in progress."
baseurl: ""
url: "https://github.com/flomertens/libwise"
github_username:  flomertens

# Build settings
markdown: kramdown
permalink: pretty
